### ISSUE TITLE
Messages are all getting logged as 'Info' level

### ISSUE THREAD

**Issue by SimonSDA** [FantasticFiasco/serilog-sinks-udp#151]
I have the following appsettings.json settings for the Udp sink, using Log2Console as the viewer for testing:

	"Serilog": {
		"Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Udp" ],
		"MinimumLevel": {
			"Default": "Verbose",
			"Override": {
				"Microsoft": "Error",
				"Microsoft.Hosting.Lifetime": "Information",
				"System": "Debug",
				"Hangfire": "Warning"
			}
		},
		"WriteTo": [
			{
				"Name": "Console",
				"Args": {
					"outputTemplate": "{Timestamp} [{Level}] {Message}{NewLine:1} - {Exception}"
				}
			},
			{
				"Name": "Udp",
				"Args": {
					"remoteAddress": "localhost",
					"remotePort": 7071,
					"family": "InterNetwork"
				}
			}
		],
		"Enrich": [ "FromLogContext", "WithMachineName", "WithProcessId", "WithThreadId" ],
		"Properties": { "Application": "SeriLogger" }
	}
}

With these settings it should log at Verbose level, however all messages are coming in as Information, no matter what the level (see screenshot for examples).

**To Reproduce**

1. Create a simple console application (in my case .NET Framework 4.8) with Serilog and the Udp sink configured as above.
2. Create a log with LogVerbose and another with LogInformation.
3. Configure a Udp sink in e.g. Log2Console with the above settings.
4. Both logs Messages show the correct log level, but the Level itself for both messages is Information.

**Expected behavior**

The 'Verbose' message should have had 'Verbose' level.

**Screenshots**

![UdpLog](https://user-images.githubusercontent.com/26325173/229768308-25dee0c8-fa25-4221-9bb6-2191e4cc3ded.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version: 22H2 (19045.2728)

**Additional context**

.NET version: .NET Framework 4.8
Serilog version: 2.12.0
Serilog.Sinks.Udp version: 8.0.1

**Comment by FantasticFiasco** [comment]
Hi @SimonSDA!

As I recall it you need to use the [Log4jTextFormatter](https://github.com/FantasticFiasco/serilog-sinks-udp#log4jtextformatter) if you wan't to receive the UDP packages in Log2Console. As your configuration currently is specified, I would assume that [the following extension](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/src/Serilog.Sinks.Udp/LoggerSinkConfigurationExtensions.cs#L74) is found by Serilog when searching for a factory method compatible with your settings. I think you also need to specify the `formatter`, [as we do in the tests](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/test/Serilog.Sinks.Udp.Tests/appsettings_text_formatter_ipv4.json#L14), but in our case I would assume the fulle name to be something like `"Serilog.Sinks.Udp.TextFormatters.Log4jTextFormatter, Serilog.Sinks.Udp"`.

**Comment by FantasticFiasco** [comment]
You can't expect [Serilog.Sinks.Configuration](https://github.com/serilog/serilog-settings-configuration) to magically find an extension method that doesn't exist. This sink provides two sink extension method, both found [in this file](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/src/Serilog.Sinks.Udp/LoggerSinkConfigurationExtensions.cs). Neither of them takes all of your specified configuration (`remoteAddress`, `remotePort`, `family`, `outputTemplate` and `formatter`). You can only specify arguments that match one of the extension methods, not pick arguments from both extensions and expect it to just work.

What I assume is happening here is that [Serilog.Sinks.Configuration](https://github.com/serilog/serilog-settings-configuration), based on your provided arguments, selects the extension method that accepts `outputTemplate`, which means that it disregards the `formatter` configuration.

**Comment by SimonSDA** [comment]
Ok that makes sense. So it sounds like its not possible to have it use the Log4TextFormatter with a custom outputTemplate then.

**Comment by FantasticFiasco** [comment]
That is correct, but I believe you can write your own formatter to produce the same message. Copy [Log4jTextFormatter](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/src/Serilog.Sinks.Udp/Sinks/Udp/TextFormatters/Log4jTextFormatter.cs) to your project and the replace [line 125](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/src/Serilog.Sinks.Udp/Sinks/Udp/TextFormatters/Log4jTextFormatter.cs#L125) with whatever is neccessary to produce your expected output.

**Comment by SimonSDA** [comment]
Thanks - will give that a go :)
