### ISSUE TITLE
Version 9 does not work with Serilog.Sinks.PeriodicBatching 4.0.0

### ISSUE THREAD

**Issue by sergey-messer** [FantasticFiasco/serilog-sinks-udp#196]
Try to add 
Serilog.Sinks.Udp 9
Serilog.Sinks.Mail 3  (with dependence Serilog.Sinks.PeriodicBatching >=4.0.0)
in same project 

Get Exception

Could not load type 'Serilog.Sinks.Udp.Private.BatchingSink' from assembly 'Serilog.Sinks.Udp, Version=9.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' because the parent type is sealed.

**Comment by FantasticFiasco** [comment]
I've published a new version that will fix this issue, see [v10.0.0](https://www.nuget.org/packages/Serilog.Sinks.Udp/10.0.0).

Thanks for reporting it!
