### ISSUE TITLE
Log4netTextFormatter generates invalid XML

### ISSUE THREAD

**Issue by alkampfergit** [FantasticFiasco/serilog-sinks-udp#21]
In Log4netTextFormatter class, xml start with

` output.Write("<log4net:event");`

But actually the namespace log4net is never declared, the XML generated is invalid.

Possible and simple fix is removing the namespace entirely.

**Comment by FantasticFiasco** [comment]
I will take a look at it. I was influenced by the log4net logger, but have to make sure that I'm not doing anything the log4net logger isn't.

Thanks for notifying me!

**Comment by FantasticFiasco** [comment]
An official version (v4.0.1) of the package has been uploaded to nuget.org.

Sorry it took this long to fix the issue!

**Comment by alkampfergit** [comment]
Thanks.

--
Gian Maria Ricci
Cell: +39 320 0136949

<http://mvp.microsoft.com/en-us/mvp/Gian%20Maria%20Ricci-4025635>
<http://www.linkedin.com/in/gianmariaricci>  <https://twitter.com/alkampfer>
  <http://feeds.feedburner.com/AlkampferEng>
