### ISSUE TITLE
Configure using host name instead of ip address only

### ISSUE THREAD

**Issue by marekstachura** [FantasticFiasco/serilog-sinks-udp#26]
Hello,

I'd like to add the change to the `LoggerSinkConfigurationExtensions` to be able to resolve the ip address of the host name passed as `remoteAddress`.

I'm thinking of adding an extension method for `string` similar to:

```csharp
public static IPAddress ToIPAddress(this string remoteAddress)
{
    if(IPAddress.TryParse(remoteAddress, out var ipAddress))
    {
        return ipAddress;
    }

    var hostEntry = Dns.GetHostEntry(remoteAddress);
    return hostEntry.AddressList.First();
}
```

And then make a change in the `LoggerSinkconfigurationExtensions.cs` from:
```csharp
public static LoggerConfiguration Udp(
    this LoggerSinkConfiguration sinkConfiguration,
    string remoteAddress,
    int remotePort,
    int localPort = 0,
    LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
    LoggingLevelSwitch levelSwitch = null,
    string outputTemplate = DefaultOutputTemplate,
    IFormatProvider formatProvider = null)
{
    return Udp(
        sinkConfiguration,
        IPAddress.Parse(remoteAddress),
        remotePort,
        localPort,
        restrictedToMinimumLevel,
        levelSwitch,
        outputTemplate,
        formatProvider);
}
```

to:
```csharp
public static LoggerConfiguration Udp(
    this LoggerSinkConfiguration sinkConfiguration,
    string remoteAddress,
    int remotePort,
    int localPort = 0,
    LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
    LoggingLevelSwitch levelSwitch = null,
    string outputTemplate = DefaultOutputTemplate,
    IFormatProvider formatProvider = null)
{
    return Udp(
        sinkConfiguration,
        remoteAddress.ToIPAddress(),
        remotePort,
        localPort,
        restrictedToMinimumLevel,
        levelSwitch,
        outputTemplate,
        formatProvider);
}
```

At the moment when I try to pass the host name in the configuration it throws `FormatException: An invalid IP address was specified.`

Let me know if that makes sense.
Thanks.

**Comment by FantasticFiasco** [comment]
I'll take a look at it, I'll have to verify that the change won't be a breaking change.

The obvious workaround would be for you to have the extension method `ToIPAddress` in your code, and make sure to pass an IP address to the sink indifferent of whether you on your end is storing the remote as an IP address or hostname.

**Comment by marekstachura** [comment]
Yes, I get that - if you want to configure the sink `in code` - but if you want to do that using the application configuration files, then it is not working at the moment.

Please see this change, that I think would fix the problem:

https://github.com/marekstachura/serilog-sinks-udp/commit/53a76766f0afab27a0230dcbf7d617470a2fd7de

**Comment by FantasticFiasco** [comment]
Ok, I get that, I'll look at the code.

**Comment by marekstachura** [comment]
Fantastic! I will make sure to do what you suggested. Thanks.

**Comment by FantasticFiasco** [comment]
Np, looking forwards to working with you.

At the end when we are finished you will squash all commits into a single one, and thus will be one of the contributors to this sinks. I hope you agree to that.

**Comment by marekstachura** [comment]
Hey, I created https://github.com/FantasticFiasco/serilog-sinks-udp/pull/27 - should we move the discussion over there?
I'm not entirely sure if I should test this functionality like I did - I think could just try to build the logger and test this with one simple test - not sure.
From your checklist I think I'm still missing the bit about the documentation.

Looking forward to your feedback.

**Comment by FantasticFiasco** [comment]
Yes, lets move the discussion to #27

**Comment by FantasticFiasco** [comment]
There is a NuGet package available with version `4.1.0-release-4-1-0-beta-1-00603`. Can you install it and see if it fits your needs before I officially release it?

**Comment by TDabasinskas** [comment]
Not the original requester, but just to let you know that I've tried the beta package with the following configuration and it's working just fine:

```json
{
        "name": "Udp",
        "args": {
          "remoteAddress": "logs.example.com",
          "remotePort": 12643,
          "formatter": "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact",
          "restrictedToMinimumLevel": "Information"
        }
      }
```

Thank you!

**Comment by marekstachura** [comment]
Hey, I had few days break, will try to test today if this is working for me.

**Comment by FantasticFiasco** [comment]
Np, nobody is in a hurry :-)

**Comment by marekstachura** [comment]
It is working for me! Thanks!

**Comment by FantasticFiasco** [comment]
I'll see if I get time to release it tonight, or else it will be tomorrow.

Thanks for letting me know about this issue, and for implementing the code yourself :grin:

**Comment by FantasticFiasco** [comment]
There is now an official version released on nuget.org
