### ISSUE TITLE
Configuration for Log2Console

### ISSUE THREAD

**Issue by agatlin** [FantasticFiasco/serilog-sinks-udp#28]
I am having difficultly configuring the serilog-sinks-udp to work with log2console. I understand log2console expects the input to be in log4jformat. I am just not certain how to configure serilog-sinks-udp to make that happen.

Do you happen to have a sample configuration that works with log2console?

Thank you!

**Comment by FantasticFiasco** [comment]
Have you tried specifying an instance of `Log4jTextFormatter` when you configure the sink? For more information about the formatter, see [here](https://github.com/FantasticFiasco/serilog-sinks-udp#log4jtextformatter).

**Comment by agatlin** [comment]
@FantasticFiasco Mattias, I am using ASP.NET Core 2.0. I am unsure how I am supposed to specify an instance of the `Log4jTextFormatter`. 

My configuration is like so.

            var formatter = new Log4jTextFormatter();

            Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Verbose()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Verbose)
            .Enrich.FromLogContext()
            .WriteTo.Udp(IPAddress.Loopback, 7071, formatter)            
            .WriteTo.Console()
            .WriteTo.File("log.txt",
                rollingInterval: RollingInterval.Day,
                rollOnFileSizeLimit: true)            
            .CreateLogger();

I had seen the information on the `Log4jTextFormatter` but I was unsure if I needed to do anything with it or how I might use it.

<log4j:event logger="Some.Serilog.Context" timestamp="1184286222308" level="ERROR" thread="1">
  <log4j:message>Something failed</log4j:message>
  <log4j:throwable>An exception describing the failure<log4j:throwable>
</log4j:event>

My log file has plenty of entries but `Log2Console` has nothing. I have the standard UDP receiver configured.

Thank you for your help!

**Comment by FantasticFiasco** [comment]
The configuration seems to be correct.

- Can you verify that nothing is printed in the [Serilog SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics#selflog)?
- Do you have any firewall blocking the UDP packeages?

**Comment by agatlin** [comment]
Serilog is logging to a local file without incident.  `Log2Console` is enabled in the firewall. (Just as a sanity check, I turned Windows Firewall off to be sure.) I am not seeing any errors anywhere.

I added code for SelfLog as below. The `serilog-out.txt` file is being created but nothing is populated, so I am assuming there was nothing to write. 

```
var file = File.CreateText("serilog-out.txt");
SelfLog.Enable(TextWriter.Synchronized(file));
```
I am obviously doing something wrong, but I have no idea what it is.

**Comment by FantasticFiasco** [comment]
I can build a sample, ready for you to run, in five hours or so. Are you running on .NET Framework or Core?

**Comment by agatlin** [comment]
@FantasticFiasco Mattias, that is very kind of you. I am running under ASP.NET Core 2.1. Thank you so very much for you help! Tack så mycket!

**Comment by FantasticFiasco** [comment]
Wow you know some Swedish, nice! :D

**Comment by FantasticFiasco** [comment]
I've updated `README.md` with a chapter called _Sample applications_. That chapter contains a link to the sample application.

I've verified that the sample works on my computer running Windows 10 Pro version 1803. Please let me know if it doesn't work on your machine.

**Comment by agatlin** [comment]
@FantasticFiasco Mattias, thank you for the sample application. The sample `console application` worked perfectly and displayed the log messages in `Log2Console` just as expected.

However, the same settings still are not working in `ASP.NET Core 2.1`. I am still investigating, but I am not sure why. 

Log messages are properly being written through `Serilog` to a log file--so we know that `Serilog` is functional. The `SelfLog` output still shows no errors. Nothing makes its way from `ASP.NET Core 2.1` into `Log2Console`.

**Comment by FantasticFiasco** [comment]
Oh, sorry, how stupid of me, I've built the wrong sample application :-( Give me an hour...

**Comment by FantasticFiasco** [comment]
I've updated the new repository with a Web API sample application.

**Comment by agatlin** [comment]
@FantasticFiasco, Mattias, Thank you so much! Your code works perfectly! I found the problem on my end. I will go ahead and document it here just in case any one else faces a similar issue.

I have just started using Docker and was testing my app locally in a Docker container running on windows. I forgot that the Docker container gets its own IP address. Since Log2Console was running on my PC, it did not match the IP Address defined in the default configuration.

`.WriteTo.Udp(IPAddress.Loopback, 7071, new Log4jTextFormatter())`

Once I updated the IP Address in the configuration (where `xxx.xxx.xxx.xxxx` is a valid value for an IPAddress), then everything worked just fine.

`.WriteTo.Udp(IPAddress.Parse("xxx.xxx.xxx.xxx"), 7071, new Log4jTextFormatter())`

It is possible to use Log2Console even when developing and testing with Docker. That is awesome!

Thank you again so much for all your help!

**Comment by FantasticFiasco** [comment]
Ah, that makes sense! Docker is running its host on a separate network interface on Windows. I would bet money that your code would work perfectly fine on Linux, because there the Docker host is sharing the network interface with the operating system.

I think you should try specifying an address in the [multicast range](http://www.tcpipguide.com/free/t_IPMulticastAddressing.htm). With multicast the UDP packages _should_ traverse the network interfaces and reach Log2Console.

Should we close this issue?
