### ISSUE TITLE
Remote hostname resolved only once

### ISSUE THREAD

**Issue by nbaztec** [FantasticFiasco/serilog-sinks-udp#29]
### Step 1: Describe your environment

* Ubuntu 18.04
* .NET core 2.1.401
  
### Step 2: Describe the problem
Currently the UDP Sink supports a hostname as a destination in the configuration. Due to the implementation however the hostname is resolved _only once_ at the application startup. This effectively removes the advantages associated with using hostnames since any future changes to the DNS won't be adjusted by the application at all. 

#### Steps to reproduce:

1. Setup a local hostname `foobar.local` via `/etc/hosts/`. Point it to a locally available UDP listener (service, etc.). For example, running on `192.168.1.100`.
2. Start a test application with the UDP sink and the value `remoteAddress`  = `foobar.local` in the configuration. Keep it running so it's sending contant packets to the UDP listener service.
3. Verify that the packets are being received.
4. Terminate the UDP listener and move it to a different host. For example to `192.168.1.200`.
5. Adjust the `/etc/hosts` to point `foobar.local` to the new IP `192.168.1.200`.
6. The running test application would no longer adapt to the moved UDP listening service and would still be sending to the old IP since it does not use the hostname beyond the setup stage.
  
#### Observed results

* Since the IP resolution was done at startup time, the hostname is meaningless in the logging context.
  
#### Expected results

* The UDP packets should've been sent to the hostname, irrespective of the IP change without restarting the Logging application.

**Comment by FantasticFiasco** [comment]
I think you are correct. I will look at the PR tonight, lets get this embarresing issue solved as soon as possible.

Thanks for reporting the issue!

**Comment by nbaztec** [comment]
No worries, glad to help :)
