### ISSUE TITLE
System.Net.Sockets.UdpClient bug causing issues

### ISSUE THREAD

**Issue by nbaztec** [FantasticFiasco/serilog-sinks-udp#34]
It seems there is a bug in .net core corefx library which is triggered in the following case:

- `System.Net.Sockets.UdpClien`t uses hostname
- The hostname has only IPv4 address associated to it

The bug would effectively ignore the address (and not select it) if the Socket is running in IPv6+DualMode since it filters on the `AddressFamily` of the socket. This information is actually impossible to infer from a hostname, since a hostname can have multiple IPs, a combination of both IPv4 and IPv6.

I've submitted them the fix https://github.com/dotnet/corefx/issues/32475, however I felt that you need to be aware of this as well and take appropriate actions regarding the current release, which would fail under that specific case.

**Comment by FantasticFiasco** [comment]
Thanks!

We'll leave this issue open until it is solved in .NET.

Thanks for reporting it!

**Comment by nbaztec** [comment]
Closed via dotnet/corefx#32504.

**Comment by FantasticFiasco** [comment]
Thanks for pursuing this issue!
