### ISSUE TITLE
Message is not parsed from Log2Console when Exception is logged

### ISSUE THREAD

**Issue by aquasonic** [FantasticFiasco/serilog-sinks-udp#45]
I'm using .NET Core and have configured Serilog as follow:

```cs
Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();
```

With `appsettings.json`:

```json
"Serilog": {
    "Using": [ "Serilog.Sinks.Udp" ],
    "WriteTo": [
      {
        "Name": "Udp",
        "Args": {
          "remoteAddress": "127.0.0.1",
          "remotePort": 7071,
          "formatter": "Serilog.Sinks.Udp.TextFormatters.Log4jTextFormatter, Serilog.Sinks.Udp, Version=5.0.1.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10"
        }
      }
    ]
  }
```

So everything works fine and my logs appear correctly in Log2Console when I do something like that:

```cs
public class AppController : Controller
{
    private readonly ILogger<AppController> logger;

    public AppController(ILogger<AppController> logger)
    {
        this.logger = logger;
    }

    public string Test()
    {
        this.logger.LogError("This is my test error");

        return "test";
    }
}
```
But when I change the code to the following, then the message in Log2Console is not parsed correctly.

```cs
public string Test()
{
    try
    {
        int.Parse("lala");
    }
    catch (Exception exception)
    {
        this.logger.LogError(exception, "This is my test error");
    }

    return "test";
}
```
in Log2Console I see the following message, marked an **Info**:

```
CallSiteClass: 
CallSiteMethod: 
File: 
Line: 0
<log4j:event xmlns:log4j="http://jakarta.apache.org/log4j/" logger="Api.Controllers.AppController" timestamp="1560851914474" level="ERROR"><log4j:message>This is my test error</log4j:message><log4j:throwable>System.FormatException: Input string was not in a correct format.

   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)

   at System.Int32.Parse(String s)

   at Api.Controllers.AppController.Test() in C:\Development\Api\Controllers\AppController.cs:line 22</log4j:throwable></log4j:event>
```

I'm using .NET Core 2.2 with Serilog 2.1.1 and Serilog.Sinks.Udp 5.0.1.

Am I missing something on the configuration or is there something wrong in the pattern? 

Thanks for looking into it and best regards,
Kevin

**Comment by FantasticFiasco** [comment]
Hi and welcome to Serilog.Sinks.Udp!

It looks like you've found a bug, I will look into this issue tonight, it seems that it should be easy to reproduce.

Thank you for reporting it!

**Comment by FantasticFiasco** [comment]
Due to your detailed description I had no problems finding the issue. I was not escaping XML characters (`<`, `>`, `&`) in the exception message, thus producing illegal XML.

I'm in the process of merging the fix to master, and will then start working towards a release. Thank you for reporting the issue!

**Comment by FantasticFiasco** [comment]
It will take some time for an official version with your fix to be released. If you are being blocked, I would recommend you to copy the code found in [Log4jTextFormatter](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/src/Serilog.Sinks.Udp/Sinks/Udp/TextFormatters/Log4jTextFormatter.cs), renaming the class to `MyLog4jTextFormatter` or something similar and remove the class once the new official version has been released.

**Comment by aquasonic** [comment]
Thanks for the very fast fix and the proposed workaround until the new release. Glad I could help :)

**Comment by FantasticFiasco** [comment]
There is a [new pre-release available on www.nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0-beta3), with a fix for your issue.

Would you be able to validate that the formatter in the pre-release works as expected? You will have to make some changes to your configuration of the UDP sink, please see the migration instructions [here](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/CHANGELOG.md#dizzy-changed).

**Comment by aquasonic** [comment]
This works as expected, thank you :)

**Comment by FantasticFiasco** [comment]
Perfect!

I will have to await confirmation from another user before I release a new official version, but I hope it shouldn't take that long, unless he has vacation, but then I'll release the new version anyway.

Thanks for the support! Keep up the good work!

**Comment by FantasticFiasco** [comment]
Release v6.0.0 is now live on [nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0).

Thank you for reporting the issue!
