### ISSUE TITLE
Unable to configure the sink using Serilog.Settings.Configuration

### ISSUE THREAD

**Issue by bonejon** [FantasticFiasco/serilog-sinks-udp#5]
Within our dot netcore web application we use the Setilog configuration library to allow different logging configuration per environment. When trying to add this sink to the project and configure this way it crashes with the following error:

    Invalid cast from 'System.String' to 'System.Net.IPAddress'.

The fix is to add an additional extension method that receives the ip address as a string and converts is using IPAddress.Parse(remoteAddress). I have created a PR for this https://github.com/FantasticFiasco/serilog-sinks-udp/pull/4

**Comment by FantasticFiasco** [comment]
Nice!

I'll take a look at it tonight and create a new release.

**Comment by FantasticFiasco** [comment]
A [pre-release](https://www.nuget.org/packages/Serilog.Sinks.UDP/2.2.0-vnext-00201) is ready for you. Would it be possible for you to install it and verify that is solves your issue?

Thanks in advance!

**Comment by bonejon** [comment]
Hi,

Just installed the prerelease and it works perfectly, thank you. 

There is an interesting subtlety in the code that I forgot to comment. The serilog configuration loader finds the extension methods by reflection and only examines the parameter names not types, it then does a FirstOrDefault() on the return results. With this in mind, for the code submitted to work as expected the string overload of the extension method needs to be defined first in the class, either that or we give the parameter a unique name.

**Comment by FantasticFiasco** [comment]
I think we should give the parameter a unique name to eliminate the risk of me reordering the methods in the future. I'll update the code in a couple of hours, and then publish an official version.

Thank you for the feedback!

**Comment by FantasticFiasco** [comment]
The official version 2.2.0 is now published to NuGet. You will have to change the argument name in your JSON from `remoteAddress` to `remoteAddressAsString`, but then everything should work exactly as in the beta.

If you find the release satisfying, please close this issue.

Thank you very much for bringing the issue to my attention, and for contributing to this project. You are now mentioned in the [change log](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/CHANGELOG.md).
