### ISSUE TITLE
Log4netTextFormatter does not escape message containing XML

### ISSUE THREAD

**Issue by mkb137** [FantasticFiasco/serilog-sinks-udp#51]
**Describe the bug**
The Log4netTextFormatter does not escape a log message containing XML special characters.  For example, 
```
Log.Debug( "Do<Something>")
```
will result in XML like:
```
<log4net:message>Do<Something></log4net:message>
```
Tools attempting to parse the XML will fail.

**Expected behavior**
The XML should be escaped, as in:
```
<log4net:message>Do&lt;Something&gt;</log4net:message>
```

**Additional context**
I'm using a customized version of Sentinel as the log reader (https://github.com/mkb137/Sentinel)

**Comment by FantasticFiasco** [comment]
Thanks! I'll look into this tonight, but I am currently on holiday and won't probably release a new version until the weekend. Will you be able to work around the issue?

**Comment by mkb137** [comment]
Yes, no problem.

**Comment by FantasticFiasco** [comment]
There is a [new pre-release available on www.nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0-beta4), with a fix for your issue.

Would you be able to validate that the pre-release works as you'd expect? You will have to make some changes to your configuration of the UDP sink, please see the migration instructions [here](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/CHANGELOG.md#dizzy-changed).

**Comment by mkb137** [comment]
I tried it and confirmed that it works.

**Comment by FantasticFiasco** [comment]
Release v6.0.0 is now live on [nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0).

Thank you for reporting the issue!

**Comment by mkb137** [comment]
If you want to add it to your documentation, this is how you configure the sink in app.config settings:
		<add key="serilog:using:Udp" value="Serilog.Sinks.Udp" />
		<add key="serilog:write-to:Udp"/>
		<add key="serilog:write-to:Udp.remoteAddress" value="127.0.0.1"/>
		<add key="serilog:write-to:Udp.remotePort" value="9998"/>
		<add key="serilog:write-to:Udp.family" value="InterNetwork"/>
		<add key="serilog:write-to:Udp.formatter" value="Serilog.Sinks.Udp.TextFormatters.Log4netTextFormatter, Serilog.Sinks.Udp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10"/>

**Comment by FantasticFiasco** [comment]
Thanks! I've updated the readme with your provided configuration.

Best wishes to you on your coding journey!
