### ISSUE TITLE
NetStandard 1.3 and csproj migration

### ISSUE THREAD

**Issue by scottamartin** [FantasticFiasco/serilog-sinks-udp#7]
### Step 1: Describe your environment

* Develop on OS X and Windows
* Run code on Windows and Ubuntu
  
### Step 2: Describe the problem

I would like to migrate the project to the new csproj format and downgrade the NetStandard reference to 1.3 to match Serilog.  From what I can tell 1.3 is the lowest this library could use due to needing System.Net.Sockets.

**Comment by FantasticFiasco** [comment]
Hi scottamartin! 

That would be a fantastic contribution. I assume that also would include migrating solution file to VS2017?

**Comment by scottamartin** [comment]
Yes, that is correct.  As far as the build script goes I would would need to update the image for AppVeyor to VS2017 and that would allow for the removal of the "install" portion.

**Comment by FantasticFiasco** [comment]
Removing code is my favorite type of implementation, just knock yourself out.

And again, thanks for the time and effort you put into this.

**Comment by FantasticFiasco** [comment]
How is the code treating you, are encountering any problems in the migration? If you desire I can team up with you and help you push this code to production.

**Comment by scottamartin** [comment]
Everything is going well, I ran into a larger than normal workload this week.  The "dotnet migration" tool is not working, so I am manually converting the project to csproj.  I am going to try and devote some time to this today and over this weekend.

**Comment by scottamartin** [comment]
@FantasticFiasco PR has been submitted, let me know if you see anything.  I am able to run the build and tests on my windows machine (cmd line and Visual Studio 2017).  I am also able to restore, build, and test on my mac using the "-f netstandard1.3" flag to specify the framework.

**Comment by scottamartin** [comment]
Added.

I was going to ask you about your opinion on keeping the AssemblyInfo.cs or moving it all to the csproj file.  That way the build will auto generate it.  If you need anything on the build script side and versioning let me know.  I actively use CAKE for all of my .NET Core projects to allow for cross platform builds.
