### ISSUE TITLE
.Trim() ruins OutputTemplate={NewLine} 

### ISSUE THREAD

**Issue by tagcode** [FantasticFiasco/serilog-sinks-udp#73]
UdpSink calls .Trim() which removes {NewLine} behaviour and makes it impossible to formulate the message as the user wants.

**Comment by FantasticFiasco** [comment]
Correct me if I’m wrong, but it only removes all leading and trailing white-space characters. Is it a trailing whitespace that is removed in your application?

**Comment by tagcode** [comment]
Yes, trailing whitespace is removed. I'm using OutputTemplate="{EventId}{NewLine}" and capturing it with netcat in a bash script. The script cannot distinguish different lines because "{NewLine}" is consumed by the sender. Similarly, OutputTemplate="{Message}{NewLine}" also sends endless blocks of texts without linefeed.

**Comment by FantasticFiasco** [comment]
I'll look into it, cant remember why I added it, bit since changing it would be a breaking change I have to investigate it further.

**Comment by tagcode** [comment]
Okay. I suppose you considered packet boundary as equivalent information to whitespace/linefeed. 

I think the options here are:
- New _major_ version line and having the breaking change there, which is considered acceptable so long the change informed in readme.
- More configuration options (not elegant).

**Comment by FantasticFiasco** [comment]
A new major version with your fix is now available on nuget.org, you've also been mentioned in the changelog.

Thank you for reporting this!

**Comment by tagcode** [comment]
👍 Tried it and it works now exactly as in OutputTemplate. I appreciate.
